//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.1
//     from Assets/Sources/Client/Combat/Infrastructure/Input/CombatInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Client.Combat.Infrastructure.Input
{
    public partial class @CombatInput: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @CombatInput()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""CombatInput"",
    ""maps"": [
        {
            ""name"": ""CombatMovement"",
            ""id"": ""cd24e949-ca96-4b50-8ff7-4126fc38e5bf"",
            ""actions"": [
                {
                    ""name"": ""MoveCharacter"",
                    ""type"": ""Value"",
                    ""id"": ""d5dc7475-e88a-46d4-8cab-64992d060c1d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LockCursor"",
                    ""type"": ""Button"",
                    ""id"": ""9916ccaf-255e-450b-bfbd-84d5f9178696"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""2ef989f8-82ca-4eaa-b794-05ff84cd9d23"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveCharacter"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""798dd686-8a37-4a4a-81ba-18efe180c77a"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""MoveCharacter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""bfdc515b-0112-44d1-a5a2-1ac971dddc7e"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""MoveCharacter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""afb18722-8f02-4caf-8f64-7f71b0d34882"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""MoveCharacter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""e8c8bb84-91b0-405b-a167-aec7b73e6af0"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""MoveCharacter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""dbf56aec-18f2-4e32-a61a-235c1623033d"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""MoveCharacter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""364d0482-f9ba-4cf1-ac28-5191d6c79adf"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LockCursor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""CombatCasting"",
            ""id"": ""7e7f7731-fbc1-43bf-a530-35be70bfac14"",
            ""actions"": [
                {
                    ""name"": ""CastAbility1"",
                    ""type"": ""Button"",
                    ""id"": ""f47f339e-52c8-4585-990b-a0a2a4b0767a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CastAbility2"",
                    ""type"": ""Button"",
                    ""id"": ""0c6db217-cacb-4411-8ccd-3057395da043"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CastAbility3"",
                    ""type"": ""Button"",
                    ""id"": ""eb6ef794-53b3-460b-8f54-42d561553769"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CastAbility4"",
                    ""type"": ""Button"",
                    ""id"": ""4d2265d9-a6d2-4af3-a837-d802b6d5b4c9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CastAbility5"",
                    ""type"": ""Button"",
                    ""id"": ""bc43199a-0e78-4bcb-926e-cb3aeb502710"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CastAbility6"",
                    ""type"": ""Button"",
                    ""id"": ""bd011827-bb9c-4559-96b8-396fdbae8363"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""0b58632d-26f2-4b50-9837-f6902975eac1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b7e0768e-0112-44ba-8296-63b1087d74b7"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""CastAbility1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""39497656-0d96-4c2e-a9ac-69fe13d450b4"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""CastAbility1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c9350a94-cd93-406e-8359-3b80e0eea81f"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""CastAbility2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""662ccef5-aff5-4d1c-9aa4-d60a0b0abc6f"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""CastAbility2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""83d36888-d62a-446e-810a-a046a2a19d40"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""CastAbility3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""430d43ea-05dd-4254-abaa-afbde2f4ce01"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""CastAbility3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c30f2c44-5f65-463b-bf82-1639c96f668e"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CastAbility4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5c082968-e92c-4e28-93c9-39347a38af93"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""CastAbility4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9f92c2f4-8d1e-4018-8b41-0df977762084"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""CastAbility5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9b0eaec4-5cbf-42f8-b999-a3ee56937965"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""CastAbility5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""13a8a8d4-e5f5-4bc7-90bc-f02f6fbad89f"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""CastAbility6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4aea0f5d-7696-4d2f-821c-76223e0516b8"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""CastAbility6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2f5eb43c-bea3-45e3-8850-070108f3d703"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""66521ed8-86ff-41cc-bdef-7c3c10cca14d"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""CombatTargeting"",
            ""id"": ""93d6df67-d546-466a-8958-c5078cd9a3ff"",
            ""actions"": [
                {
                    ""name"": ""SellectTarget"",
                    ""type"": ""Button"",
                    ""id"": ""d52be580-9a38-4427-8200-534f4413e74e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ControlNext"",
                    ""type"": ""Button"",
                    ""id"": ""7f363d96-9cd0-42ff-a6e6-31e2171af71c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TargetNext"",
                    ""type"": ""Button"",
                    ""id"": ""cf62f09c-8d5d-4618-9264-a9f633dcfac7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""783f9511-3d92-4101-89b4-749bdb6a728a"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""SellectTarget"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b7c0f2b2-c676-4eac-a6bb-bba4b76733f9"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""ControlNext"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""43bccbed-c39b-4db4-8d83-160c32ca31b6"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""ControlNext"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""287b2eb5-6e89-4285-9660-4ed1f8d083cc"",
                    ""path"": ""<Mouse>/backButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""TargetNext"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""edaaa6fb-ef97-428a-a20e-03e77aa252de"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TargetNext"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Camera"",
            ""id"": ""d564d8e8-580c-457d-a9b9-56a5b6874a09"",
            ""actions"": [
                {
                    ""name"": ""MoveCamera"",
                    ""type"": ""Value"",
                    ""id"": ""063c355e-6703-495d-87ed-feea18f2a60b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""DistantCamera"",
                    ""type"": ""Value"",
                    ""id"": ""43ef0f62-1197-4f39-9c6d-eaee22328179"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""970f94d4-cbf2-407f-b3c6-7f15c5ac0272"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""MoveCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""b6639ad7-9669-46e0-b562-2574542c7bbd"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveCamera"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""346aeda9-410e-4617-a373-9f3825aa396d"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""MoveCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""e652543c-144f-41bf-9a5e-83c3de945545"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""MoveCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""ac4d0b6a-c257-4da2-9224-3bac74a0abcd"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""DistantCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": []
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": []
        }
    ]
}");
            // CombatMovement
            m_CombatMovement = asset.FindActionMap("CombatMovement", throwIfNotFound: true);
            m_CombatMovement_MoveCharacter = m_CombatMovement.FindAction("MoveCharacter", throwIfNotFound: true);
            m_CombatMovement_LockCursor = m_CombatMovement.FindAction("LockCursor", throwIfNotFound: true);
            // CombatCasting
            m_CombatCasting = asset.FindActionMap("CombatCasting", throwIfNotFound: true);
            m_CombatCasting_CastAbility1 = m_CombatCasting.FindAction("CastAbility1", throwIfNotFound: true);
            m_CombatCasting_CastAbility2 = m_CombatCasting.FindAction("CastAbility2", throwIfNotFound: true);
            m_CombatCasting_CastAbility3 = m_CombatCasting.FindAction("CastAbility3", throwIfNotFound: true);
            m_CombatCasting_CastAbility4 = m_CombatCasting.FindAction("CastAbility4", throwIfNotFound: true);
            m_CombatCasting_CastAbility5 = m_CombatCasting.FindAction("CastAbility5", throwIfNotFound: true);
            m_CombatCasting_CastAbility6 = m_CombatCasting.FindAction("CastAbility6", throwIfNotFound: true);
            m_CombatCasting_Attack = m_CombatCasting.FindAction("Attack", throwIfNotFound: true);
            // CombatTargeting
            m_CombatTargeting = asset.FindActionMap("CombatTargeting", throwIfNotFound: true);
            m_CombatTargeting_SellectTarget = m_CombatTargeting.FindAction("SellectTarget", throwIfNotFound: true);
            m_CombatTargeting_ControlNext = m_CombatTargeting.FindAction("ControlNext", throwIfNotFound: true);
            m_CombatTargeting_TargetNext = m_CombatTargeting.FindAction("TargetNext", throwIfNotFound: true);
            // Camera
            m_Camera = asset.FindActionMap("Camera", throwIfNotFound: true);
            m_Camera_MoveCamera = m_Camera.FindAction("MoveCamera", throwIfNotFound: true);
            m_Camera_DistantCamera = m_Camera.FindAction("DistantCamera", throwIfNotFound: true);
        }

        ~@CombatInput()
        {
            UnityEngine.Debug.Assert(!m_CombatMovement.enabled, "This will cause a leak and performance issues, CombatInput.CombatMovement.Disable() has not been called.");
            UnityEngine.Debug.Assert(!m_CombatCasting.enabled, "This will cause a leak and performance issues, CombatInput.CombatCasting.Disable() has not been called.");
            UnityEngine.Debug.Assert(!m_CombatTargeting.enabled, "This will cause a leak and performance issues, CombatInput.CombatTargeting.Disable() has not been called.");
            UnityEngine.Debug.Assert(!m_Camera.enabled, "This will cause a leak and performance issues, CombatInput.Camera.Disable() has not been called.");
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // CombatMovement
        private readonly InputActionMap m_CombatMovement;
        private List<ICombatMovementActions> m_CombatMovementActionsCallbackInterfaces = new List<ICombatMovementActions>();
        private readonly InputAction m_CombatMovement_MoveCharacter;
        private readonly InputAction m_CombatMovement_LockCursor;
        public struct CombatMovementActions
        {
            private @CombatInput m_Wrapper;
            public CombatMovementActions(@CombatInput wrapper) { m_Wrapper = wrapper; }
            public InputAction @MoveCharacter => m_Wrapper.m_CombatMovement_MoveCharacter;
            public InputAction @LockCursor => m_Wrapper.m_CombatMovement_LockCursor;
            public InputActionMap Get() { return m_Wrapper.m_CombatMovement; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(CombatMovementActions set) { return set.Get(); }
            public void AddCallbacks(ICombatMovementActions instance)
            {
                if (instance == null || m_Wrapper.m_CombatMovementActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_CombatMovementActionsCallbackInterfaces.Add(instance);
                @MoveCharacter.started += instance.OnMoveCharacter;
                @MoveCharacter.performed += instance.OnMoveCharacter;
                @MoveCharacter.canceled += instance.OnMoveCharacter;
                @LockCursor.started += instance.OnLockCursor;
                @LockCursor.performed += instance.OnLockCursor;
                @LockCursor.canceled += instance.OnLockCursor;
            }

            private void UnregisterCallbacks(ICombatMovementActions instance)
            {
                @MoveCharacter.started -= instance.OnMoveCharacter;
                @MoveCharacter.performed -= instance.OnMoveCharacter;
                @MoveCharacter.canceled -= instance.OnMoveCharacter;
                @LockCursor.started -= instance.OnLockCursor;
                @LockCursor.performed -= instance.OnLockCursor;
                @LockCursor.canceled -= instance.OnLockCursor;
            }

            public void RemoveCallbacks(ICombatMovementActions instance)
            {
                if (m_Wrapper.m_CombatMovementActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(ICombatMovementActions instance)
            {
                foreach (var item in m_Wrapper.m_CombatMovementActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_CombatMovementActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public CombatMovementActions @CombatMovement => new CombatMovementActions(this);

        // CombatCasting
        private readonly InputActionMap m_CombatCasting;
        private List<ICombatCastingActions> m_CombatCastingActionsCallbackInterfaces = new List<ICombatCastingActions>();
        private readonly InputAction m_CombatCasting_CastAbility1;
        private readonly InputAction m_CombatCasting_CastAbility2;
        private readonly InputAction m_CombatCasting_CastAbility3;
        private readonly InputAction m_CombatCasting_CastAbility4;
        private readonly InputAction m_CombatCasting_CastAbility5;
        private readonly InputAction m_CombatCasting_CastAbility6;
        private readonly InputAction m_CombatCasting_Attack;
        public struct CombatCastingActions
        {
            private @CombatInput m_Wrapper;
            public CombatCastingActions(@CombatInput wrapper) { m_Wrapper = wrapper; }
            public InputAction @CastAbility1 => m_Wrapper.m_CombatCasting_CastAbility1;
            public InputAction @CastAbility2 => m_Wrapper.m_CombatCasting_CastAbility2;
            public InputAction @CastAbility3 => m_Wrapper.m_CombatCasting_CastAbility3;
            public InputAction @CastAbility4 => m_Wrapper.m_CombatCasting_CastAbility4;
            public InputAction @CastAbility5 => m_Wrapper.m_CombatCasting_CastAbility5;
            public InputAction @CastAbility6 => m_Wrapper.m_CombatCasting_CastAbility6;
            public InputAction @Attack => m_Wrapper.m_CombatCasting_Attack;
            public InputActionMap Get() { return m_Wrapper.m_CombatCasting; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(CombatCastingActions set) { return set.Get(); }
            public void AddCallbacks(ICombatCastingActions instance)
            {
                if (instance == null || m_Wrapper.m_CombatCastingActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_CombatCastingActionsCallbackInterfaces.Add(instance);
                @CastAbility1.started += instance.OnCastAbility1;
                @CastAbility1.performed += instance.OnCastAbility1;
                @CastAbility1.canceled += instance.OnCastAbility1;
                @CastAbility2.started += instance.OnCastAbility2;
                @CastAbility2.performed += instance.OnCastAbility2;
                @CastAbility2.canceled += instance.OnCastAbility2;
                @CastAbility3.started += instance.OnCastAbility3;
                @CastAbility3.performed += instance.OnCastAbility3;
                @CastAbility3.canceled += instance.OnCastAbility3;
                @CastAbility4.started += instance.OnCastAbility4;
                @CastAbility4.performed += instance.OnCastAbility4;
                @CastAbility4.canceled += instance.OnCastAbility4;
                @CastAbility5.started += instance.OnCastAbility5;
                @CastAbility5.performed += instance.OnCastAbility5;
                @CastAbility5.canceled += instance.OnCastAbility5;
                @CastAbility6.started += instance.OnCastAbility6;
                @CastAbility6.performed += instance.OnCastAbility6;
                @CastAbility6.canceled += instance.OnCastAbility6;
                @Attack.started += instance.OnAttack;
                @Attack.performed += instance.OnAttack;
                @Attack.canceled += instance.OnAttack;
            }

            private void UnregisterCallbacks(ICombatCastingActions instance)
            {
                @CastAbility1.started -= instance.OnCastAbility1;
                @CastAbility1.performed -= instance.OnCastAbility1;
                @CastAbility1.canceled -= instance.OnCastAbility1;
                @CastAbility2.started -= instance.OnCastAbility2;
                @CastAbility2.performed -= instance.OnCastAbility2;
                @CastAbility2.canceled -= instance.OnCastAbility2;
                @CastAbility3.started -= instance.OnCastAbility3;
                @CastAbility3.performed -= instance.OnCastAbility3;
                @CastAbility3.canceled -= instance.OnCastAbility3;
                @CastAbility4.started -= instance.OnCastAbility4;
                @CastAbility4.performed -= instance.OnCastAbility4;
                @CastAbility4.canceled -= instance.OnCastAbility4;
                @CastAbility5.started -= instance.OnCastAbility5;
                @CastAbility5.performed -= instance.OnCastAbility5;
                @CastAbility5.canceled -= instance.OnCastAbility5;
                @CastAbility6.started -= instance.OnCastAbility6;
                @CastAbility6.performed -= instance.OnCastAbility6;
                @CastAbility6.canceled -= instance.OnCastAbility6;
                @Attack.started -= instance.OnAttack;
                @Attack.performed -= instance.OnAttack;
                @Attack.canceled -= instance.OnAttack;
            }

            public void RemoveCallbacks(ICombatCastingActions instance)
            {
                if (m_Wrapper.m_CombatCastingActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(ICombatCastingActions instance)
            {
                foreach (var item in m_Wrapper.m_CombatCastingActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_CombatCastingActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public CombatCastingActions @CombatCasting => new CombatCastingActions(this);

        // CombatTargeting
        private readonly InputActionMap m_CombatTargeting;
        private List<ICombatTargetingActions> m_CombatTargetingActionsCallbackInterfaces = new List<ICombatTargetingActions>();
        private readonly InputAction m_CombatTargeting_SellectTarget;
        private readonly InputAction m_CombatTargeting_ControlNext;
        private readonly InputAction m_CombatTargeting_TargetNext;
        public struct CombatTargetingActions
        {
            private @CombatInput m_Wrapper;
            public CombatTargetingActions(@CombatInput wrapper) { m_Wrapper = wrapper; }
            public InputAction @SellectTarget => m_Wrapper.m_CombatTargeting_SellectTarget;
            public InputAction @ControlNext => m_Wrapper.m_CombatTargeting_ControlNext;
            public InputAction @TargetNext => m_Wrapper.m_CombatTargeting_TargetNext;
            public InputActionMap Get() { return m_Wrapper.m_CombatTargeting; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(CombatTargetingActions set) { return set.Get(); }
            public void AddCallbacks(ICombatTargetingActions instance)
            {
                if (instance == null || m_Wrapper.m_CombatTargetingActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_CombatTargetingActionsCallbackInterfaces.Add(instance);
                @SellectTarget.started += instance.OnSellectTarget;
                @SellectTarget.performed += instance.OnSellectTarget;
                @SellectTarget.canceled += instance.OnSellectTarget;
                @ControlNext.started += instance.OnControlNext;
                @ControlNext.performed += instance.OnControlNext;
                @ControlNext.canceled += instance.OnControlNext;
                @TargetNext.started += instance.OnTargetNext;
                @TargetNext.performed += instance.OnTargetNext;
                @TargetNext.canceled += instance.OnTargetNext;
            }

            private void UnregisterCallbacks(ICombatTargetingActions instance)
            {
                @SellectTarget.started -= instance.OnSellectTarget;
                @SellectTarget.performed -= instance.OnSellectTarget;
                @SellectTarget.canceled -= instance.OnSellectTarget;
                @ControlNext.started -= instance.OnControlNext;
                @ControlNext.performed -= instance.OnControlNext;
                @ControlNext.canceled -= instance.OnControlNext;
                @TargetNext.started -= instance.OnTargetNext;
                @TargetNext.performed -= instance.OnTargetNext;
                @TargetNext.canceled -= instance.OnTargetNext;
            }

            public void RemoveCallbacks(ICombatTargetingActions instance)
            {
                if (m_Wrapper.m_CombatTargetingActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(ICombatTargetingActions instance)
            {
                foreach (var item in m_Wrapper.m_CombatTargetingActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_CombatTargetingActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public CombatTargetingActions @CombatTargeting => new CombatTargetingActions(this);

        // Camera
        private readonly InputActionMap m_Camera;
        private List<ICameraActions> m_CameraActionsCallbackInterfaces = new List<ICameraActions>();
        private readonly InputAction m_Camera_MoveCamera;
        private readonly InputAction m_Camera_DistantCamera;
        public struct CameraActions
        {
            private @CombatInput m_Wrapper;
            public CameraActions(@CombatInput wrapper) { m_Wrapper = wrapper; }
            public InputAction @MoveCamera => m_Wrapper.m_Camera_MoveCamera;
            public InputAction @DistantCamera => m_Wrapper.m_Camera_DistantCamera;
            public InputActionMap Get() { return m_Wrapper.m_Camera; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(CameraActions set) { return set.Get(); }
            public void AddCallbacks(ICameraActions instance)
            {
                if (instance == null || m_Wrapper.m_CameraActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_CameraActionsCallbackInterfaces.Add(instance);
                @MoveCamera.started += instance.OnMoveCamera;
                @MoveCamera.performed += instance.OnMoveCamera;
                @MoveCamera.canceled += instance.OnMoveCamera;
                @DistantCamera.started += instance.OnDistantCamera;
                @DistantCamera.performed += instance.OnDistantCamera;
                @DistantCamera.canceled += instance.OnDistantCamera;
            }

            private void UnregisterCallbacks(ICameraActions instance)
            {
                @MoveCamera.started -= instance.OnMoveCamera;
                @MoveCamera.performed -= instance.OnMoveCamera;
                @MoveCamera.canceled -= instance.OnMoveCamera;
                @DistantCamera.started -= instance.OnDistantCamera;
                @DistantCamera.performed -= instance.OnDistantCamera;
                @DistantCamera.canceled -= instance.OnDistantCamera;
            }

            public void RemoveCallbacks(ICameraActions instance)
            {
                if (m_Wrapper.m_CameraActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(ICameraActions instance)
            {
                foreach (var item in m_Wrapper.m_CameraActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_CameraActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public CameraActions @Camera => new CameraActions(this);
        private int m_KeyboardSchemeIndex = -1;
        public InputControlScheme KeyboardScheme
        {
            get
            {
                if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
                return asset.controlSchemes[m_KeyboardSchemeIndex];
            }
        }
        private int m_GamepadSchemeIndex = -1;
        public InputControlScheme GamepadScheme
        {
            get
            {
                if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
                return asset.controlSchemes[m_GamepadSchemeIndex];
            }
        }
        public interface ICombatMovementActions
        {
            void OnMoveCharacter(InputAction.CallbackContext context);
            void OnLockCursor(InputAction.CallbackContext context);
        }
        public interface ICombatCastingActions
        {
            void OnCastAbility1(InputAction.CallbackContext context);
            void OnCastAbility2(InputAction.CallbackContext context);
            void OnCastAbility3(InputAction.CallbackContext context);
            void OnCastAbility4(InputAction.CallbackContext context);
            void OnCastAbility5(InputAction.CallbackContext context);
            void OnCastAbility6(InputAction.CallbackContext context);
            void OnAttack(InputAction.CallbackContext context);
        }
        public interface ICombatTargetingActions
        {
            void OnSellectTarget(InputAction.CallbackContext context);
            void OnControlNext(InputAction.CallbackContext context);
            void OnTargetNext(InputAction.CallbackContext context);
        }
        public interface ICameraActions
        {
            void OnMoveCamera(InputAction.CallbackContext context);
            void OnDistantCamera(InputAction.CallbackContext context);
        }
    }
}
